---
version: "2.1"

services:
  db:
    image: mongo:4.2.0-bionic
    restart: always
    volumes:
      - "./dbdata:/data/db"
    healthcheck:
      test: echo 'db.stats().ok' | mongo localhost:27017/shieldy --quiet
      interval: 5s
      timeout: 5s
      retries: 12
  app:
    image: tg-bot-penetrator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TOKEN: "${TOKEN}"
      MONGO: mongodb://db:27017/shieldy
    depends_on:
      db:
        condition: service_healthy
